---

- hosts: redhat_servers
  gather_facts: yes
# gather_subset: min
  become: yes
  tasks:

    - name: Execute a shell command
      ansible.builtin.shell: modinfo i915 | grep ^ver
      register: command_output

    - name: Display command output
      debug:
        var: command_output.stdout_lines

