---

- hosts: all
  become: true
  tasks:

  - name: install updates Redhat
    tags: always
    yum:
      name: '*'
      state: latest
      update_cache: yes
    when: ansible_distribution == "RedHat" or ansible_distribution == "Red Hat Enterprise Linux" 

  - name: install updates Debian
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"

- hosts: debian_servers
  become: true
  tasks:

  - name: install unzip
    package: 
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: redhat_servers
  become: true
  tasks:

  - name: install apache and php for RedHat
    tags: RedHat,httpd,php
    yum:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "RedHat" or ansible_distribution == "Red Hat Enterprise Linux"

  - name: copy default html file for site
    tags: RedHat,httpd,php
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: debian_servers
  become: true
  tasks:

  - name: install apache2 and php for Debian
    tags: Debian,apache2
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Debian"
