---

- hosts: all
  become: true
  tasks:

  - name: install apache and php for RedHat
    yum:
      name: 
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "RedHat" or ansible_distribution == "Red Hat Enterprise Linux"

  - name: install apache2 and php for Debian
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Debian"
