- name: install updates Redhat
  yum:
    name: '*'
    state: latest
    update_cache: yes

- name: install apache and php for RedHat
  yum:
    name:
      - httpd
      - php
    state: latest

- name: copy default html file for site
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
